### ISSUE TITLE
/usr/lib/ruby/2.1.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/ruby/data/geoip/country_code.yml (Errno::ENOENT)

### ISSUE THREAD

**Issue by dimpol** [tsu-iscd/beef-drive#1]
Hi guys,
I completed the setup procedure as you suggested but i keep on receiving the following error when i submit the ruby beef command. Any thoughts on how i can solve this?

PS: Installation takes place on a clean Kali Linux 2.0 OS.

/usr/lib/ruby/2.1.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/ruby/data/geoip/country_code.yml (Errno::ENOENT)

**Comment by dnkolegov** [comment]
Hello.
Did you try to install and run the last versions of original BeEF? Is that issue reproduced there?

**Comment by dimpol** [comment]
It was a path problem. It was my fault you can close this one. Can you check the new issue regarding : /root/Downloads/arsenal/beef-drive/extensions/gdrive/gdrive.rb:87:in `block in start_init_server': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by dnkolegov** [comment]
Thanks.

**Comment by dnkolegov** [comment]
Hey @dimpol.
Could you please describe how did you solve the issues 1 and 2?
Maybe it will be useful for other.

**Comment by SYANiDE-** [comment]
Link the directory "data" with where it's actually located. 

### Find country_code.yml:
$ updatedb
$ locate country_code.yml
## OR ##
find / -type f -name country_code.yml -exec ls -al {} \;

output:  
/usr/share/ruby-geoip/geoip/country_code.yml
/var/lib/gems/2.3.0/gems/geoip-1.6.3/data/geoip/country_code.yml


### FIX:
ln -s /var/lib/gems/2.3.0/gems/geoip-1.6.3/data  /usr/lib/ruby/data

**Comment by dnkolegov** [comment]
Great.
Thanks.
