### ISSUE TITLE
/root/Downloads/arsenal/beef-drive/extensions/gdrive/gdrive.rb:87:in `block in start_init_server': undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dimpol** [tsu-iscd/beef-drive#2]
I also tried again on a clean kali linux 2.0 OS.

The following error occurred.
Any thoughts?

/root/Downloads/arsenal/beef-drive/extensions/gdrive/gdrive.rb:87:in `block in start_init_server': undefined method `each' for nil:NilClass (NoMethodError)

PS: I get answers,init and keychain.txt ID's from the copy link for sharing function of google drive. I hope that is correct...

**Comment by dnkolegov** [comment]
Thanks for the report.
We are looking into this.

**Comment by dimpol** [comment]
My pleasure.. Beef-drive is a truly great way to simulate red team tactics.

**Comment by dimpol** [comment]
Sorry for the many messages... I am really unsure about setting the gdrive and gdrive ID's correctly.
Can you please elaborate on that? I mean how to get the folder and keychain.txt ID's. Are there any special configurations which must be done in the gdrive?

**Comment by dimpol** [comment]
Hi, i also tried setting up beef-drive on a clean Ubuntu 14.04. I got the exact shame error.... /home/bougidi/Downloads/beef-drive/extensions/gdrive/gdrive.rb:87:in `block in start_init_server': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by dimpol** [comment]
I am closing this issue i figured it out.

**Comment by dimpol** [comment]
The refresh token i hardcoded was already used.
