### ISSUE TITLE
Acquire refresh token and auth token necessity questions.

### ISSUE THREAD

**Issue by dimpol** [tsu-iscd/beef-drive#3]
Can you please elaborate on how to acquire the refresh token and if auth token should be hardcoded too? you don't mention something regarding the auth token and i keep receiving 401 when beef hook tries to communicate with google drive

**Comment by dnkolegov** [comment]
Hello @dimpol.
Sorry for delay. At the present time our team is taking part in a security conference. We will back to you soon.
Thanks.

P.S. All hardcoded tokens and IDs are listed in the `core/main/client/gdrive.js`.

**Comment by dimpol** [comment]
I totally understand.... Beef-drive is great. The only thing needed is a nicer documentation regarding how to setup gdrive in general (any gdrive configurations, how obtain the refresh token, setup authorization token, enable the gdrive api in general). I still haven't figured all those out...so i am waiting for your return...

**Comment by neoleksov** [comment]
Hello @dimpol.

First at all, you should go to [google developers console](https://console.developers.google.com), create project and get OAuth 2.0 client ID and client secret.

Then, you should [send two http requests](https://www.themarketingtechnologist.co/google-oauth-2-enable-your-application-to-access-data-from-a-google-user/). 

The first one gives you `code` (the authorization code from the GET request), which will be used in the next request.

The second one return you `refresh token`. To make this request  you should send  `code` from the first request as a POST parameter.

It's important that the only first request with `client id`, `client secret` and `code` will return `refresh token`, all other requests will return only `access token`.

**Comment by dnkolegov** [comment]
Closed.
